#!/usr/bin/env python
# Copyright (C) 2014 Colin Walters <walters@verbum.org>
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place - Suite 330,
# Boston, MA 02111-1307, USA.

import os
import sys
import tempfile
import subprocess
from gi.repository import Gio, OSTree

print "%r" % (sys.argv, )
selfdir=os.path.dirname(sys.argv[0])

proc = subprocess.Popen(['/bin/sh', '-c', '. ' + selfdir + '/config.sh; env'], stdout=subprocess.PIPE)
for line in proc.stdout:
    k,v = line.split('=', 1)
    v = v.rstrip()
    print "%s = %s" % (k, v)
    os.environ[k] = v

os.environ['SRCDIR'] = selfdir + '/..'

repo = OSTree.Repo(path=Gio.File.new_for_path(os.environ['OSTREE_REPO']))
repo.open(None)

_,origrev = repo.resolve_rev(os.environ['REF'], True)

subprocess.check_call(['rpm-ostree', 'compose', 'tree', '--repo=' + os.environ['OSTREE_REPO'],
                       '--cachedir=' + os.environ['RPMOSTREE_CACHEDIR'],
                       os.environ['SRCDIR'] + '/' + os.environ['OSNAME'] + '-' + os.environ['TREENAME'] + '.json'])
_,newrev = repo.resolve_rev(os.environ['REF'], True)
if origrev != newrev:
    print "%s => %s" % (os.environ['REF'], newrev)
    os.environ['REV'] = newrev
    subprocess.check_call([selfdir + '/create-disks.sh'])
else:
    print "%s is unchanged at %s" % (os.environ['REF'], origrev)

